### ISSUE TITLE
MacOS Sierra: Crash upon insertion of CH340 device

### ISSUE THREAD

**Issue by dylanmc** [himalayanelixir/Arduino_USB_Drivers#1]
After installing this driver, when I insert my CH340 USB device, my kernel crashes to a grey-screen with text explaining "your system has crashed". Bummer!

**Comment by himalayanelixir** [comment]
Hey, I uploaded the latest drivers. You should first uninstall the current ones using the instructions in the readme and then try these ones out.

**Comment by dylanmc** [comment]
I confirm the new driver both doesn't crash my machine, and communicates great with my CH340. Thanks!!

**Comment by himalayanelixir** [comment]
np! Thanks for letting me know.
